### ISSUE TITLE
请问微信推文里的反量化这里的意思是？

### ISSUE THREAD

**Issue by foreverlms** [netease-youdao/EMLL#1]
![image](https://user-images.githubusercontent.com/20502148/122156033-bca2bf80-ce9a-11eb-96e5-58029ef5020b.png)

https://mp.weixin.qq.com/s/qiS_DSpkaX_mCNpvLgeS-Q

**Comment by foreverlms** [comment]
为什么是int32->float32呢？

**Comment by netease-youdao** [comment]
反量化是指把gemm或其他计算得到的int8或int32的值还原到float32，抱歉推文中写的不全面，应该是int8/int32 -> float32
量化矩阵乘法是int8*int8 -> int32, 可以直接把int32 反量化成float32， 也可以int32 重量化成int8，再反量化成float32，可根据实际计算需求决定

**Comment by foreverlms** [comment]
> 反量化是指把gemm或其他计算得到的int8或int32的值还原到float32，抱歉推文中写的不全面，应该是int8/int32 -> float32
> 量化矩阵乘法是int8*int8 -> int32, 可以直接把int32 反量化成float32， 也可以int32 重量化成int8，再反量化成float32，可根据实际计算需求决定

thanks，请问为啥不是和下面的量化反过来呢？我还以为是好几个int8或者int16组成int32运算呢:laugh

**Comment by netease-youdao** [comment]
> > 反量化是指把gemm或其他计算得到的int8或int32的值还原到float32，抱歉推文中写的不全面，应该是int8/int32 -> float32
> > 量化矩阵乘法是int8*int8 -> int32, 可以直接把int32 反量化成float32， 也可以int32 重量化成int8，再反量化成float32，可根据实际计算需求决定
> 
> thanks，请问为啥不是和下面的量化反过来呢？我还以为是好几个int8或者int16组成int32运算呢:laugh

是的，和量化是反向过程的
