### ISSUE TITLE
如何在编译EMLL时选择性打开GEMM的某种优化手段？

### ISSUE THREAD

**Issue by xuhaoguang** [netease-youdao/EMLL#10]
通过EMLL的介绍，GEMM的优化主要有 分块、重排 和 汇编优化 三个手段，请问如何选择性的让其中某个或者某几个手段生效呢？

因为我自测发现，同一份数据在单独写demo在设备上测试是没问题的，但是集成到项目中，在设备上测试，会出core，经分析大概率是由于内存不足导致，所以怀疑对于GEMM的三个优化手段，是不是有些优化手段非常耗费内存？

**Comment by netease-youdao** [comment]
EMLL目前会使用一些buffer存放重排的数据，最大不超过1MB，可以通过调整include/common/下面头文件中GEMM_D_xxx和GEMM_R_xxx等参数来调整它们的大小。如果要完全免去这些buffer，需要修改include/common/CommonDriver.h和include/common/CommonSkinny*.h中的代码，目前暂未设置宏开关。
