### ISSUE TITLE
使用EMLL比OpenBlas+RUY的方式多使用10M内存

### ISSUE THREAD

**Issue by kismit** [netease-youdao/EMLL#13]
一 实验背景: 
基于ctranslator2框架适配EMLL, 跑翻译demo(int8), 对比基于EMLL推理和OpenBlas+RUY推理的速度和内存使用情况
EMLL版本: https://github.com/netease-youdao/EMLL/issues/9#issuecomment-939259322
已经应用patch: https://github.com/netease-youdao/EMLL/issues/8#issuecomment-903630259

二 C++ bin demo
① EMLL矩阵计算
内存: 102M
速度: 约380-500ms
②Openblas + RUY矩阵计算
内存: 107M
速度: 约680-720ms

三 Qt集成
单独跑bin demo速度和内存上都没啥问题,但是集成到qt应用上基于EMLL方式的内存占用会比基于Openblas+RUY的方式多出10M,
两者除了矩阵这块其他程序和输入都是一样

请问这种情况有可能是什么原因导致?

**Comment by kismit** [comment]
这边查看到的情况是集成EMLL版本的so后空跑进程是26.7M, 但是集成openblas+ruy版本的so后空跑是8M,  内存的差距应该是在so依赖本身?

**Comment by netease-youdao** [comment]
感谢您的关注。关于内存的问题，可能是有些用于存放重排矩阵块的数组以固定大小放在了线程本地存储（TLS）上所致，您可以尝试使用[memory-omp-fix](https://github.com/netease-youdao/EMLL/tree/memory-omp-fix)分支的代码编译应用（其中把这些数组改放到了栈上），看是否有所改善。

**Comment by kismit** [comment]
有效, 内存占用和Openblas+RUY的方式基本一样了,感谢!
