### ISSUE TITLE
sgemm找不到

### ISSUE THREAD

**Issue by dlkht** [netease-youdao/EMLL#15]
还有人维护吗
编译好之后，测试sgemm函数，提示找不到

**Comment by netease-youdao** [comment]
请问在编译出的库的函数符号中能看到sgemm吗？（用编译工具链的nm可以查看）如果有的话是什么性质（T/t/w/U/...）？

**Comment by dlkht** [comment]
> 请问在编译出的库的函数符号中能看到sgemm吗？（用编译工具链的nm可以查看）如果有的话是什么性质（T/t/w/U/...）？

你好！谢谢解答。编译出的库的函数符号中有sgemm这个符号，但想和paddle-lite比较下性能，连上paddle-lite编译时提示undefined reference to `sgemm'，我在EMLL中加入一个空函数 替代sgemm，再编译EMLL，然后连上paddle-lite编译就通过

**Comment by dlkht** [comment]
你们能否提供一个实现sgemm代码实例，比如A53 CPU的

**Comment by netease-youdao** [comment]
直接调用sgemm就行，里面会自动检测CPU的种类。调用方法可以看说明文档(doc/Usage_ZH.md)中的矩阵乘法部分，以及sgemm的函数注释(include/Gemm.h)。

**Comment by dlkht** [comment]
谢谢！测试了float32乘法，和paddle lite的速度差不多，不知道是不是这样

**Comment by netease-youdao** [comment]
说明大家都做了充分的性能优化:)
