### ISSUE TITLE
c 矩阵为什么要强制列优先,在很多上下文相关的场景处理不方便

### ISSUE THREAD

**Issue by TPcoding** [netease-youdao/EMLL#4]
1.是为了更好的性能而设计的吗?
2. 另外可以开源全连接层的量化版本吗? (matmul+bias +activation)
3. cnn相关的量化可否也开源

**Comment by netease-youdao** [comment]
感谢您对EMLL的关注~
C矩阵行优先的版本以及CNN和Activation会在以后的版本整合。目前C矩阵行优先可以用列优先的转置等价调用做。
