### ISSUE TITLE
A53平台速度比arm compute library慢

### ISSUE THREAD

**Issue by TPcoding** [netease-youdao/EMLL#5]
我试了这样的一个流程,Android aarch64 a53
quantize_symmetric_f32_s8
s8s32gemm
requantize_symmetric_32to8
s8s32gemm
requantize_symmetric_32to8
....   s8s32gemm 和requantize_symmetric_32to8 这样循环数层
dequantize_symmetric_f32_s32
矩阵m*n=(m*k)x(k*n), 大概分布是这样的几个矩阵m=8,k=100,n=400; m=8,k=400,n=100;
速度差不多是acl的两倍.
A76平台上多个矩阵是比acl快一点的,很赞.
看到a35,a53,a7x是有不同的代码优化的

**Comment by netease-youdao** [comment]
感谢使用和反馈，欢迎交流

**Comment by netease-youdao** [comment]
您好，标题“A53平台速度比arm compute library慢”是不是写错了，慢->快？

**Comment by TPcoding** [comment]
a53平台的确是慢,这几天我正在分析.
是不是芯片的cpuinfo和cache size 一下细节信息读取错误,导致优化没有生效?
之前的的一个经验armv8.2-a sdot 没有生效的时候,会显著慢. 
但是a53 系列的Android 没有neon相关的特殊指令编译选项.我特意用了官方的release库也对比了一次,还是慢.
如果下周方便的话我可以贴一个benchmark代码

**Comment by netease-youdao** [comment]
抱歉，还是没有明白您说的是EMLL慢还是acl慢？您标题写的“A53平台速度比arm compute library慢”，正文中写的是“速度差不多是acl的两倍.”  两个地方矛盾

> 我试了这样的一个流程,Android aarch64 a53
> quantize_symmetric_f32_s8
> s8s32gemm
> requantize_symmetric_32to8
> s8s32gemm
> requantize_symmetric_32to8
> .... s8s32gemm 和requantize_symmetric_32to8 这样循环数层
> dequantize_symmetric_f32_s32
> 矩阵m_n=(m_k)x(k*n), 大概分布是这样的几个矩阵m=8,k=100,n=400; m=8,k=400,n=100;
> 速度差不多是acl的两倍.
> A76平台上多个矩阵是比acl快一点的,很赞.
> 看到a35,a53,a7x是有不同的代码优化的

**Comment by TPcoding** [comment]
抱歉,我表达的有问题.在我上面几个矩阵的综合表现上看,acl只要emll一半的运行时间就可以完成. a53 emll的确是比acl慢.

**Comment by netease-youdao** [comment]
> 抱歉,我表达的有问题.在我上面几个矩阵的综合表现上看,acl只要emll一半的运行时间就可以完成. a53 emll的确是比acl慢.

能具体描述下EMLL和acl上具体测试方法吗，或提供下benchmark代码，我们复现下，多谢

**Comment by TPcoding** [comment]
[res.tar.gz](https://github.com/netease-youdao/EMLL/files/6798096/res.tar.gz)
acl的矩阵prepare复用,在emll上面没有体现到,层复用的时候会重复权重矩阵的重排工作吧?

**Comment by netease-youdao** [comment]
EMLL v1.0 暂不支持预重排的方法。目前对于量化的矩阵乘法，EMLL v1.0 在A53上对于m=8的扁平情况尚未使用汇编级别优化。我们会在以后的版本加入这些功能，感谢您的关注。
