### ISSUE TITLE
openmp如何打包到so中

### ISSUE THREAD

**Issue by bcmi220** [netease-youdao/EMLL#6]
您好，按照使用说明在配置中添加-fopenmp以使用openmp，由于需要把所有的计算库作为so提供给实际应用，所以当前通过objdump -x查看so还是依赖于openmp，请问有什么推荐的配置可以打包到so么？

**Comment by netease-youdao** [comment]
有些工具链的openmp没法整合到编译的库中，需要在运行时动态链接，只要保证交叉编译的工具链版本和端侧的openmp动态库一致即可。

**Comment by bcmi220** [comment]
我在交叉编译的工具链中看到了openmp的存在，但是移动到具体平台上进行运行的时候就报缺少openmp so的错误，有什么好的做法么。
另外有没有使用和不使用openmp的性能对比情况啊。
感谢您的回答。

**Comment by netease-youdao** [comment]
请检查一下端侧的openmp库的位置（比如shell运行find / -name "libgomp*" 2>/dev/null），如果不存在，需要把工具链的openmp动态库拷贝到端侧的动态库文件夹。
在矩阵乘法中，多数情况下MNK > 10000000 在端侧能明显观察到多线程的加速。您可以用test_emll_gemm程序进行测试。

**Comment by bcmi220** [comment]
对于安卓这种打包为so供ndk调用的，其默认会存在openmp库么？
感谢您对于加速性能的介绍。

**Comment by netease-youdao** [comment]
可以把EMLL的动态库和版本匹配的openmp动态库打包发行到各平台

**Comment by bcmi220** [comment]
好的，非常感谢。
