### ISSUE TITLE
unknown architecture `armv8.2-a+dotprod+fp16'

### ISSUE THREAD

**Issue by ProgrammerWLY** [netease-youdao/EMLL#7]
This error occurred when I installed EMLL on the a57 platform.

**Comment by netease-youdao** [comment]
It seems that the compiler doesn't support ARMv8.2a arch.

You can try with this EMLL source package: 
[EMLL.tar.gz](https://github.com/netease-youdao/EMLL/files/6794844/EMLL.tar.gz)
(fp16 GEMM and sdot/udot disabled)

**Comment by ProgrammerWLY** [comment]
你好，运行sgemm(1, 1, A, B, C, M, N, K, 0, 16)时出现Segmentation fault。不知道是否是我的用法不对？
但单线程的sgemm可以正常运行。

**Comment by netease-youdao** [comment]
方便提供一下gdb的backtrace和disassemble的结果吗？
