### ISSUE TITLE
多线程使用emll会造成内存占用增大

### ISSUE THREAD

**Issue by Chen1399** [netease-youdao/EMLL#8]
一个进程创建了四个线程：
thread-1：执行emll的gemm (使用1个线程计算，即gemm最后一个参数为1)
thread-2：sleep
thread-3：sleep
thread-4：sleep
这比一个进程只创建一个线程：
thread-1：执行emll的gemm (使用1个线程计算，即gemm最后一个参数为1)
占用更多内存，这个增大的内存占用来源于emll，经过我的统计，每多一个线程会增加大约768kb的内存，这个是否跟CommonDriver.h中GEMM_STATIC_BUFFER这个有关，这个也刚好创建了768kb内存（1024x192x4/1024）。
想问一下我该如何解决这种问题呢，我的线程2/3/4并不需要emll的gemm运算，如何不增加该内存占用。

**Comment by Chen1399** [comment]
armv7平台

**Comment by netease-youdao** [comment]
您可以按如下方式修改include/common/CommonDriver.h，将buffer放到栈上：
```
diff --git a/include/common/CommonDriver.h b/include/common/CommonDriver.h
index 22bd3f2..72db3ff 100644
--- a/include/common/CommonDriver.h
+++ b/include/common/CommonDriver.h
@@ -74,12 +74,6 @@

 #define SCRATCH_GEMM_D_K (SCRATCH_K_CORD(GEMM_D_K - 1) + 1)

-#define GEMM_STATIC_BUFFER(gemmtype, sbtype, satype) \
-__thread __attribute__((aligned(4096))) satype\
-  blas_##gemmtype##_sa[GEMM_S_MN * SCRATCH_GEMM_D_K];\
-__thread __attribute__((aligned(4096))) sbtype\
-  blas_##gemmtype##_sb[GEMM_S_MN * SCRATCH_GEMM_D_K];
-
 /* serial driver function with packing both source matrices,
  * loop order: N { M { K } } */
 #define GEMM_SERIAL_FUNC_LM(gemmtype, atype, satype, btype, sbtype, ctype,\
@@ -89,6 +83,10 @@ static void gemmtype##_serial_lm_m##unroll_m##n##unroll_n(\
   const atype *A, const btype *B, ctype *C,\
   uint32_t M, uint32_t N, uint32_t K, ctype beta_inp) {\
 \
+  __attribute__((aligned(4096))) satype\
+    blas_##gemmtype##_sa[GEMM_D_MN * SCRATCH_GEMM_D_K];\
+  __attribute__((aligned(4096))) sbtype\
+    blas_##gemmtype##_sb[GEMM_R_MN * SCRATCH_GEMM_D_K];\
   satype * const sa = blas_##gemmtype##_sa;\
   sbtype * const sb = blas_##gemmtype##_sb;\
 \
@@ -138,6 +136,10 @@ static void gemmtype##_serial_ln_m##unroll_m##n##unroll_n(\
   const atype *A, const btype *B, ctype *C,\
   uint32_t M, uint32_t N, uint32_t K, ctype beta_inp) {\
 \
+  __attribute__((aligned(4096))) satype\
+    blas_##gemmtype##_sa[GEMM_R_MN * SCRATCH_GEMM_D_K];\
+  __attribute__((aligned(4096))) sbtype\
+    blas_##gemmtype##_sb[GEMM_D_MN * SCRATCH_GEMM_D_K];\
   satype * const sa = blas_##gemmtype##_sa;\
   sbtype * const sb = blas_##gemmtype##_sb;\
 \
@@ -193,8 +195,6 @@ static inline bool inline_gemm_par_valid(const void *A, const void *B,
 #define GEMM_SERIAL_FUNC(gemmtype, atype, satype, btype, sbtype, ctype,\
   unroll_l2, unroll_l1, skin1_maxm, skin1_maxn, skin2_maxm, skin2_maxn, ...)\
 \
-GEMM_STATIC_BUFFER(gemmtype, sbtype, satype)\
-\
 GEMM_SERIAL_FUNC_LM(gemmtype, atype, satype, btype, sbtype, ctype,\
   unroll_l2, unroll_l1)\
 \
@@ -404,6 +404,10 @@ int gemmtype(int a_rowmajor, int b_rowmajor,\
     return 0;\
   }\
 \
+  __attribute__((aligned(4096))) satype\
+    blas_##gemmtype##_sa[GEMM_S_MN * SCRATCH_GEMM_D_K];\
+  __attribute__((aligned(4096))) sbtype\
+    blas_##gemmtype##_sb[GEMM_S_MN * SCRATCH_GEMM_D_K];\
   satype * const blas_master_sa = blas_##gemmtype##_sa;\
   sbtype * const blas_master_sb = blas_##gemmtype##_sb;\
   uint32_t acopy_dim_left, bcopy_dim_left;\
```
如果发生栈溢出，可以调小该文件中的GEMM_R_MN。

**Comment by chen1399** [comment]
谢谢您的答复，我刚才试了下您说的这种方法。并没有解决那些没有调用gemm的线程去申请额外的内存。感觉很奇怪，为什么那些线程会申请内存。

**Comment by Chen1399** [comment]
> 您可以按如下方式修改include/common/CommonDriver.h，将buffer放到栈上：
> 
> ```
> diff --git a/include/common/CommonDriver.h b/include/common/CommonDriver.h
> index 22bd3f2..72db3ff 100644
> --- a/include/common/CommonDriver.h
> +++ b/include/common/CommonDriver.h
> @@ -74,12 +74,6 @@
> 
>  #define SCRATCH_GEMM_D_K (SCRATCH_K_CORD(GEMM_D_K - 1) + 1)
> 
> -#define GEMM_STATIC_BUFFER(gemmtype, sbtype, satype) \
> -__thread __attribute__((aligned(4096))) satype\
> -  blas_##gemmtype##_sa[GEMM_S_MN * SCRATCH_GEMM_D_K];\
> -__thread __attribute__((aligned(4096))) sbtype\
> -  blas_##gemmtype##_sb[GEMM_S_MN * SCRATCH_GEMM_D_K];
> -
>  /* serial driver function with packing both source matrices,
>   * loop order: N { M { K } } */
>  #define GEMM_SERIAL_FUNC_LM(gemmtype, atype, satype, btype, sbtype, ctype,\
> @@ -89,6 +83,10 @@ static void gemmtype##_serial_lm_m##unroll_m##n##unroll_n(\
>    const atype *A, const btype *B, ctype *C,\
>    uint32_t M, uint32_t N, uint32_t K, ctype beta_inp) {\
>  \
> +  __attribute__((aligned(4096))) satype\
> +    blas_##gemmtype##_sa[GEMM_D_MN * SCRATCH_GEMM_D_K];\
> +  __attribute__((aligned(4096))) sbtype\
> +    blas_##gemmtype##_sb[GEMM_R_MN * SCRATCH_GEMM_D_K];\
>    satype * const sa = blas_##gemmtype##_sa;\
>    sbtype * const sb = blas_##gemmtype##_sb;\
>  \
> @@ -138,6 +136,10 @@ static void gemmtype##_serial_ln_m##unroll_m##n##unroll_n(\
>    const atype *A, const btype *B, ctype *C,\
>    uint32_t M, uint32_t N, uint32_t K, ctype beta_inp) {\
>  \
> +  __attribute__((aligned(4096))) satype\
> +    blas_##gemmtype##_sa[GEMM_R_MN * SCRATCH_GEMM_D_K];\
> +  __attribute__((aligned(4096))) sbtype\
> +    blas_##gemmtype##_sb[GEMM_D_MN * SCRATCH_GEMM_D_K];\
>    satype * const sa = blas_##gemmtype##_sa;\
>    sbtype * const sb = blas_##gemmtype##_sb;\
>  \
> @@ -193,8 +195,6 @@ static inline bool inline_gemm_par_valid(const void *A, const void *B,
>  #define GEMM_SERIAL_FUNC(gemmtype, atype, satype, btype, sbtype, ctype,\
>    unroll_l2, unroll_l1, skin1_maxm, skin1_maxn, skin2_maxm, skin2_maxn, ...)\
>  \
> -GEMM_STATIC_BUFFER(gemmtype, sbtype, satype)\
> -\
>  GEMM_SERIAL_FUNC_LM(gemmtype, atype, satype, btype, sbtype, ctype,\
>    unroll_l2, unroll_l1)\
>  \
> @@ -404,6 +404,10 @@ int gemmtype(int a_rowmajor, int b_rowmajor,\
>      return 0;\
>    }\
>  \
> +  __attribute__((aligned(4096))) satype\
> +    blas_##gemmtype##_sa[GEMM_S_MN * SCRATCH_GEMM_D_K];\
> +  __attribute__((aligned(4096))) sbtype\
> +    blas_##gemmtype##_sb[GEMM_S_MN * SCRATCH_GEMM_D_K];\
>    satype * const blas_master_sa = blas_##gemmtype##_sa;\
>    sbtype * const blas_master_sb = blas_##gemmtype##_sb;\
>    uint32_t acopy_dim_left, bcopy_dim_left;\
> ```
> 
> 如果发生栈溢出，可以调小该文件中的GEMM_R_MN。

谢谢您的答复，我刚才试了下您说的这种方法。并没有解决那些没有调用gemm的线程去申请额外的内存。感觉很奇怪，为什么那些线程会申请内存。

**Comment by netease-youdao** [comment]
可以按如下方式修改include/common/CommonSkinnyDot.h，将更多的buffer放到栈上：
```
diff --git a/include/common/CommonSkinnyDot.h b/include/common/CommonSkinnyDot.h
index 28e6175..88d8a2e 100644
--- a/include/common/CommonSkinnyDot.h
+++ b/include/common/CommonSkinnyDot.h
@@ -346,8 +346,6 @@ static inline bool unroll_test_m##m_unroll##n##n_dim(uint32_t M, uint32_t K) {\

 #define GEMM_SKINNY_DOT_SERIAL_FUNC_NOINCINLINE(gemm, n_dim, k_mask, m_mask,\
   scratch_size, atype, btype, unroll_test) \
-__attribute__((aligned(4096))) static __thread gemm##_skinnydot_bscalar\
-  blas_skinny_dot_b_scratch_##btype##n##n_dim[scratch_size];\
 void gemm##_arowmajor_bskinny_a##atype##_b##btype##_n##n_dim(\
   const gemm##_skinnydot_ascalar *A, const gemm##_skinnydot_bscalar *B,\
   gemm##_skinnydot_cscalar *C, uint32_t M, uint32_t K,\
@@ -383,6 +381,8 @@ void gemm##_arowmajor_bskinny_a##atype##_b##btype##_n##n_dim(\
       uint32_t m_left = M;\
       MACRO_EXPANSION_M_##m_mask(GEMM_SKINNY_DOT_INLINE_CALL_LOOP, gemm, n_dim)\
     } else {\
+      __attribute__((aligned(4096))) gemm##_skinnydot_bscalar\
+        blas_skinny_dot_b_scratch_##btype##n##n_dim[scratch_size];\
       if (b_rowmajor) {\
         const gemm##_skinnydot_bscalar *b_ptr = B + k_pos * n_dim;\
         gemm##_skinnydot_bscalar *sb_ptr =\
@@ -493,6 +493,8 @@ void gemm##_arowmajor_bskinny_a##atype##_b##btype##_n##n_dim##_omp(\
   thread_args.m_B = B;\
   thread_args.m_C = C;\
   thread_args.m_M = M;\
+  __attribute__((aligned(4096))) gemm##_skinnydot_bscalar\
+    blas_skinny_dot_b_scratch_##btype##n##n_dim[scratch_size];\
   /* use the tls scratch of master thread for shared buffer */\
   gemm##_skinnydot_bscalar * const b_scratch_master =\
     blas_skinny_dot_b_scratch_##btype##n##n_dim;\
```
如果发生栈溢出，可以调小包含该文件的源文件中引用该文件宏设置的scratch_size参数。

**Comment by Chen1399** [comment]
谢谢您的答复。这样节省了更多内存，解决了其他线程申请内存情况。
